apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-metrics
  namespace: monitoring
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: nginx
  namespaceSelector:
    matchNames: [default]
  endpoints:
    - port: metrics
      interval: 30s
